TARGET = libmate.a
TOPDIR = ..
SRC = \
	matemat.c \
	twimaster.c \
	lm75.c

##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
