/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * General Setup
 */
#define CONFIG_EXPERIMENTAL 1
#undef  MCU_MEGA8
#undef  MCU_MEGA88
#undef  MCU_MEGA162
#undef  MCU_MEGA32
#define MCU_MEGA644 1
#define MCU atmega644
#define FREQ (7372800)
#define CONFIG_NORMAL 1
#undef  BOOTLOADER_SUPPORT
#undef  CONFIG_TEENSY_RFM12
#undef  CONFIG_TEENSY_ZBUS
#undef  CONFIG_TEENSY_NONETWORK
#undef  CONFIG_USB_NET
#undef  TEENSY_SUPPORT
#define ENC28J60_SUPPORT 1
#define UIP_SUPPORT 1
#define NET_SUPPORT 1

/*
 * Cryptographic functionality
 */
#undef  CRYPTO_SUPPORT
#undef  CAST5_SUPPORT
#undef  MD5_SUPPORT
#undef  SKIPJACK_SUPPORT

/*
 * Network protocols
 */
#define TCP_SUPPORT 1
#define UDP_SUPPORT 1
#define BROADCAST_SUPPORT 1
#define ICMP_SUPPORT 1
#undef  BOOTP_SUPPORT
#undef  BOOTP_TO_EEPROM_SUPPORT
#undef  DNS_SUPPORT
#undef  SYSLOG_SUPPORT
#undef  TFTP_SUPPORT
#undef  OPENVPN_SUPPORT
#undef  RFM12_RAW_SUPPORT
#undef  ZBUS_RAW_SUPPORT

/*
 * Network configuration
 */
#undef  IPV6_SUPPORT
#undef  IPV6_STATIC_SUPPORT
#define CONF_ETHERRAPE_MAC  "\xac\xde\x48\xfd\x0f\xd0"
#define CONF_HOSTNAME "ethersex"
#define CONF_ETHERRAPE_IP uip_ipaddr(ip, 10,0,0,17 )
#define CONF_ETHERRAPE_IP4_NETMASK uip_ipaddr(ip, 255,0,0,0 )
#define CONF_ETHERRAPE_IP4_GATEWAY uip_ipaddr(ip, 10,0,0,254 )

/*
 * Applications
 */

/*
 * System clock
 */
#define CLOCK_SUPPORT 1
#undef  CLOCK_CRYSTAL_SUPPORT
#undef  DCF77_SUPPORT
#define NTP_SUPPORT 1
#define CRON_SUPPORT 1
#undef  NTPD_SUPPORT
#undef  WHM_SUPPORT

/*
 * Etherrape Control Interface (ECMD)
 */
#define ECMD_PARSER_SUPPORT 1
#define ECMD_SUPPORT 1
#undef  UECMD_SUPPORT
#undef  ECMD_SERIAL_I2C_SUPPORT
#undef  ECMD_USB_SUPPORT
#define ECMD_SERIAL_SUPPORT 1
#undef  ECMD_SENDER_SUPPORT

/*
 * Character-LCD module support
 */
#define HD44780_SUPPORT 1
#undef  HD44780_ORIGINAL
#define HD44780_KS0067B 1
#undef  HD44780_READBACK
#undef  HD44780_USE_PORTC
#define LCD_SUPPORT 1
#define MATEMAT_SUPPORT 1
#undef  MDNS_SD_SUPPORT
#undef  STELLA_SUPPORT
#undef  UDP_ECHO_NET_SUPPORT

/*
 * DynDNS support
 */
#undef  DYNDNS_SUPPORT
#undef  WATCHCAT_SUPPORT

/*
 * Interfaces
 */

/*
 * RFM12 FSK transmitter
 */
#undef  RFM12_SUPPORT
#define CONFIG_NO_I2C 1
#undef  I2C_SUPPORT
#undef  I2C_SLAVE_SUPPORT
#undef  FS20_SUPPORT
#undef  RC5_SUPPORT
#define ECMD_SERIAL_USART_SUPPORT 1
#define ECMD_SERIAL_USART_USART_0 1
#define ECMD_SERIAL_USART_USE_USART 0
#undef  ECMD_SERIAL_USART_RS485_SUPPORT

/*
 * I/O support
 */
#undef  CONFIG_IO_NONE
#define PORTIO_SIMPLE_SUPPORT 1
#undef  PORTIO_SUPPORT
#undef  HC595_SUPPORT

/*
 * HC165 input expansion
 */
#undef  HC165_SUPPORT
#undef  PS2_SUPPORT
#undef  PS2_GERMAN_LAYOUT
#undef  ADC_SUPPORT
#define ONEWIRE_SUPPORT 1
#undef  NAMED_PIN_SUPPORT

/*
 * work in progress bits (enable with care)
 */
#define DATAFLASH_SUPPORT 1
#define PSOCK_SUPPORT 1
#define HTTPD_SUPPORT 1
#undef  HTTPD_AUTH_SUPPORT
#undef  CONTROL6_SUPPORT
#undef  USB_SUPPORT
#undef  ECMD_USB_SUPPORT
#undef  USB_NET_SUPPORT
#undef  SNMP_SUPPORT
