install:
	install -o root -g root -m 500 checkout.py /usr/local/bin/checkout.py
	install -o root -g root -m 500 cashier.py /usr/local/bin/cashier.py
	install -o root -g root -m 500 udev-handler.sh /usr/local/bin/udev-handler.sh
	install -o root -g root -m 644 10-mate.rules /etc/udev/rules.d/10-mate.rules
